baseURL = 'https://paradero-incierto.netlify.app/'
languageCode = 'es-PE'
title = 'Paradero desierto'
theme = 'hello-friend-ng'

paginate = 5

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

[permalinks]
    posts = "/posts/:year/:month/:slug/"

[menu]
  [[menu.main]]
    identifier = "nosotros"
    name       = "Sobre nosotros"
    url        = "nosotros/"
    weight = 1

  [[menu.main]]
    identifier = "publicaciones"
    name       = "Publicaciones"
    url        = "publicaciones/"
    weight = 2

  [[menu.main]]
    identifier = "posts "
    name       = "Blog"
    url        = "posts/"
    weight = 3


[params]

    # Textos adicionales
    homeSubtitle = "Poesía peruana"

    # Configuración adicional
    customCSS = ["/css/xtras.css"]

    # Elementos para metadatos    
    description = "Paradero desierto. Poesía peruana"
    keywords = ""
    images = ["images/xtras/Paisaje lluvia.jpg"]

    # Autor, para metadatos
    [params.author]
        name = "Paradero desierto"

    # Configuración de favicon
    [params.favicon.color]
        mask = "#1b1c1d"
        msapplication = "#1b1c1d"
        theme = "#1b1c1d"

    # Fotos para portada
    [params.portrait]
        path = "/images/xtras/Paisaje lluvia.jpg"
        alt = "Paisaje de calle limeña en plena garúa"
        maxWidth = "160px"
    
    # Siempre fíjate en los iconos sociales
    [[params.social]]
        name = "facebook"
        url = "http://facebook.com/paraderodesierto"

    [[params.social]]
        name = "instagram"
        url = "https://www.instagram.com/paradero.desierto/"

    [[params.social]]
        name = "email"
        url = "mailto:nosotros@paraderodesierto.com"

    # Logotipo
    [params.logo]
        logoMark = ">"
        logoText = "cd /paradero-desierto"
        logoCursorDisabled = true
