baseURL = 'https://example.org/'
languageCode = 'es-pe'
title = 'Paradero desierto'
theme = 'hermit-v2'

defaultContentLanguageInSubdir = false

# En caso de que quieran una sección para copyright
copyright = 'Paradero desierto'

# Siguiendo la disposición de la plantilla, solo usaremos etiquetas
[taxonomies]
	tag = 'tags'

[params.author]
	author = 'Especial'
	about = 'nosotros'

[params]
	dateform        = "Jan 2, 2006"
	dateformShort   = "Jan 2"
	dateformNum     = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04 -0700"

	readTime = false
	
	# Detalles para SEO y para página de inicio
	description = 'Poesía peruana'
	homeSubtitle = 'Poesía peruana'
	
	homeSubtitlePrinter = false
	scrollToTop = true 
	footerCopyright = 'Preguntar antes de copiar'
	
	# Revisa si los vínculos sociales funcionan
	[[params.socialLinks]]
		name = 'instagram'
		url = 'https://www.instagram.com/paradero.desierto/'
	[[params.socialLinks]]
		name = 'facebook'
		url = 'https://www.facebook.com/paraderodesierto/'
	[[params.socialLinks]]
		name = 'email'
		url = 'mailto:nosotros@paraderodesierto.com'

[menu]
	[[menu.main]]
		name = 'Nosotros'
		url = 'nosotros/'
		weight = 1
	[[menu.main]]
		name = 'Publicaciones'
		url = 'publicaciones/'
		weight = 2